### ISSUE TITLE
`plot_network_partition` reuses variable from outer scope

### ISSUE THREAD

**Issue by johandahlberg** [bdpedigo/networks-course#57]
When working through the community detection part of the material I noticed that the `plot_network_partition` was using the `node_df` from the outer scope, which made this function fail when I was applying it on some other data. Not a major thing, but I though I would suggest a fix.

However, I was unable to get the notebook to build since the data isn't in the repo, and hence I couldn't make a PR to fix it. However, I think the code below should fix the issue:

```python
def plot_network_partition(adj, node_data, partition_key):
    fig, axs = plt.subplots(1, 2, figsize=(15, 7))

    networkplot(
        adj,
        x="x",
        y="y",
        node_data=node_data.reset_index(),
        node_alpha=0.9,
        edge_alpha=0.7,
        edge_linewidth=0.4,
        node_hue=partition_key,
        node_size="degree",
        edge_hue="source",
        ax=axs[0],
    )
    _ = axs[0].axis("off")

    _ = heatmap(
        adj,
        inner_hier_labels=node_data[partition_key],
        ax=axs[1],
        cbar=False,
        cmap="Purples",
        vmin=0,
        center=None,
        sort_nodes=True,
    )

    return fig, ax
```

Excellent materials, btw. Interesting, well-written, and easy to follow. Kudos!

**Comment by bdpedigo** [comment]
Fixed https://github.com/bdpedigo/networks-course/commit/438cb37eb8b3b9ef61330933e0850c3c43a9647f thanks for the catch!

FWIW there's a link to the data source in the notebook if you do want to try to run it https://networks.skewed.de/net/polbooks#None_draw

**Comment by johandahlberg** [comment]
Thanks for the link!
